# pre
- include: firewalld.yaml
- include: iptables.yaml
- include: kernel.yaml
- include: selinux.yaml
- include: swap.yaml

# packages
- include_tasks: "packages-{{ ansible_os_family }}.yaml"
- include_vars: "{{ ansible_os_family }}.yaml"

# post
- include: configure.yaml

- name: Ensure kubelet is started and enabled at boot
  service:
    name: kubelet
    state: started
    enabled: true
