- name: "Update repo version {{ kubernetes_mayor }}"
  ansible.builtin.copy:
    content: |
      "[kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/{{ kubernetes_mayor }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/{{ kubernetes_mayor }}/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni"
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install Kubernetes
  ansible.builtin.dnf:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    disable_excludes: "{{ item.disable_excludes | default('kubernetes') }}"
  notify: Restart kubelet
  with_items: "{{ kubernetes_packages }}"
