- name: disable swap
  command: swapoff --all
  register: _swap
  changed_when: _swap.rc != 0

- name: Remove swap from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Remove none-swap from /etc/fstab
  mount:
    name: none
    fstype: swap
    state: absent
