- name: Restart iptables
  systemd:
    name: iptables
    state: restarted
    enabled: yes

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
